/**
* \brief 
* \details 
* @author Goran
* @version 1.0
* \date Jul 8, 2016
* \copyright
* This code and information is provided "as is" without warranty of
* any kind, either expressed or implied, including but not limited to
* the implied warranties of merchantability and/or fitness for a
* particular purpose.
* \par
* Copyright (c) Gauss d.o.o. All rights reserved
*/


package radiomaster.view;

import java.awt.Color;
import java.awt.Image;
import radiomaster.restful.HttpWrapper;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import radiomaster.model.ModelCountries;
import radiomaster.controllers.ControllerCountries;
import radiomaster.controllers.ControllerStations;
import radiomaster.controllers.ControllerStream;
import radiomaster.model.ModelStations;
import radiomaster.utility.Utility;


public class RadioPlayer extends javax.swing.JFrame 
                         implements HttpWrapper.OnCompletion {
    //region CLASS PARAMETERES
    
    ArrayList<String>                       countries;
    ArrayList<String>                       stations;
    DefaultListModel<ModelCountries>        defaultListModelCountries;
    DefaultListModel<ModelStations.Station> defaultListModelStations;
    List<ModelCountries>                    fromModelCountries;
    List<ModelStations.Station>             fromModelStations;
    ControllerCountries                     controllerCountries;
    ControllerStations                      controllerStations;
    ModelCountries                          modelCountries;
    ModelStations.Station                   modelStations;
    ControllerStream                        initControllerStreamInsance = 
                                            new ControllerStream();
    //endregion
    //region CLASS CONSTRUCT
    
    public RadioPlayer() throws IOException {
        initComponents();
        setTitle(Utility.APP_NAME);
        Utility.center(this);
        setResizable(false);
        getContentPane().setBackground(Color.WHITE);
        
        jLbVol.setText(Integer.toString(jSldVol.getValue()) + "%");
        initControllerStreamInsance.setGain((float) 0.8);
        jLbImageEQ.setVisible(false);
        
        countries = new ArrayList<>();
        controllerCountries = new ControllerCountries();
        napuniCountries();
        defaultListModelCountries = new DefaultListModel<>();
        for (ModelCountries mc : fromModelCountries) {
            defaultListModelCountries.addElement(mc);
        }
      
        jLcountries.setModel(defaultListModelCountries);
        this.fromModelCountries = controllerCountries.getCountries();
    }
    //ENDREGION
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLbVolumeStatic = new javax.swing.JLabel();
        jLbPlay = new javax.swing.JLabel();
        jSldVol = new javax.swing.JSlider();
        jLbStop = new javax.swing.JLabel();
        jLbVol = new javax.swing.JLabel();
        jLbYVolStatic = new javax.swing.JLabel();
        jLbImageEQ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLcountries = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLstations = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLbUrl = new javax.swing.JLabel();
        jLbStationName = new javax.swing.JLabel();
        jLbStationDesc = new javax.swing.JLabel();
        jLbStationLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLbVolumeStatic.setText("Volume:");

        jLbPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radiomaster/images/1467907386_InterfaceExpendet-07.png"))); // NOI18N
        jLbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbPlayMousePressed(evt);
            }
        });

        jSldVol.setBackground(new java.awt.Color(255, 255, 255));
        jSldVol.setValue(80);
        jSldVol.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSldVolStateChanged(evt);
            }
        });

        jLbStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radiomaster/images/1467907404_free-09.png"))); // NOI18N
        jLbStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbStopMousePressed(evt);
            }
        });

        jLbVol.setText("100%");

        jLbYVolStatic.setText("Your volume is: ");

        jLbImageEQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radiomaster/images/equalizer.gif~original2.gif"))); // NOI18N

        jLcountries.setBackground(new java.awt.Color(255, 255, 255));
        jLcountries.setForeground(new java.awt.Color(0, 0, 0));
        jLcountries.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLcountriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jLcountries);

        jLstations.setBackground(new java.awt.Color(255, 255, 255));
        jLstations.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLstationsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jLstations);

        jLabel11.setText("Choose Country");

        jLabel12.setText("Choose Station");

        jLbStationName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLbStationDesc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbImageEQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSldVol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbStationDesc)
                            .addComponent(jLbStationName)
                            .addComponent(jLbStationLogo)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLbUrl))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbPlay)
                                    .addComponent(jLbVolumeStatic))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(jLbYVolStatic)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLbVol))
                                    .addComponent(jLbStop))))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLbUrl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLbPlay)
                                    .addComponent(jLbStop))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLbVolumeStatic)
                                    .addComponent(jLbYVolStatic)
                                    .addComponent(jLbVol))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSldVol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLbImageEQ)
                                .addContainerGap())
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLbStationName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbStationDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbStationLogo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3)))))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //region EVENT METHODS
    
    private void jLcountriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLcountriesValueChanged
        modelCountries = (ModelCountries) jLcountries.getSelectedValue();
        System.out.println(modelCountries.getCountry_code());
                
        stations = new ArrayList<>();
        controllerStations = new ControllerStations();
        
        napuniStations();
        
        defaultListModelStations = new DefaultListModel<>();
        for (ModelStations.Station ms : fromModelStations) {
            defaultListModelStations.addElement(ms);
        }
        jLstations.setModel(defaultListModelStations);     
    }//GEN-LAST:event_jLcountriesValueChanged

    private void jSldVolStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSldVolStateChanged
        float setvolume = (float) (jSldVol.getValue() / (float) 100);
        System.out.println(jSldVol.getValue() + "%   " + setvolume);
        initControllerStreamInsance.setGain(setvolume);
        jLbVol.setText(Integer.toString(jSldVol.getValue()) + "%");
    }//GEN-LAST:event_jSldVolStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        initControllerStreamInsance.StopPlayingAudioStream();
    }//GEN-LAST:event_formWindowClosing

    private void jLbPlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbPlayMousePressed
        try {
            if(jLbPlay.isEnabled()) {
                initControllerStreamInsance.StopPlayingAudioStream();
                modelStations = (ModelStations.Station) jLstations
                                .getSelectedValue();
                initControllerStreamInsance.StartPlayingAudioStream(
                                            modelStations.getStream_url());
                jLbImageEQ.setVisible(true);
                jLbPlay.setEnabled(false);
                
                
                jLbStationName.setText(modelStations.getName());
                if (modelStations.getDescription() != null) {
                    jLbStationDesc.setText(modelStations.getDescription());   
                }
                else {
                    jLbStationDesc.setText("");
                }

                if (modelStations.getImage_url() != null) {
                    System.out.println(modelStations.getImage_url());
                    URL url = new URL(modelStations.getImage_url());
                    Image image = ImageIO.read(url);
                    jLbStationLogo.setIcon(new ImageIcon(image)); 
                }
                else {
                    jLbStationLogo.setIcon(null);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
          }
    }//GEN-LAST:event_jLbPlayMousePressed

    private void jLbStopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbStopMousePressed
        try {
            initControllerStreamInsance.StopPlayingAudioStream();
            jLbImageEQ.setVisible(false);
            jLbPlay.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
          }
    }//GEN-LAST:event_jLbStopMousePressed

    private void jLstationsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLstationsValueChanged
       modelStations = (ModelStations.Station) jLstations.getSelectedValue();
      // jLbUrl.setText(modelStations.getStream_url());
       jLbPlay.setEnabled(true);

    }//GEN-LAST:event_jLstationsValueChanged
    //endregion
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLbImageEQ;
    private javax.swing.JLabel jLbPlay;
    private javax.swing.JLabel jLbStationDesc;
    private javax.swing.JLabel jLbStationLogo;
    private javax.swing.JLabel jLbStationName;
    private javax.swing.JLabel jLbStop;
    private javax.swing.JLabel jLbUrl;
    private javax.swing.JLabel jLbVol;
    private javax.swing.JLabel jLbVolumeStatic;
    private javax.swing.JLabel jLbYVolStatic;
    private javax.swing.JList<ModelCountries> jLcountries;
    private javax.swing.JList<ModelStations.Station> jLstations;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSldVol;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onError(String error) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     Utility.error(this, "Nemrem BRE da pustim strim");
        

    }

    @Override
    public void onSuccess(String successBody) {

    }

    private void napuniCountries() {
        this.fromModelCountries = controllerCountries.getCountries();

    }
    
    private void napuniStations() {
        this.fromModelStations = controllerStations
                .getStations(modelCountries.getCountry_code());

    }
}
