/*
 * /**
license The MIT License

Copyright (c) 2012-2016 Gauss, www.gauss.hr

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 */
package radiomaster.view;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import radiomaster.model.model_categories;
import radiomaster.model.model_subcategories;
import radiomaster.restful.HttpWrapper;
import static radiomaster.restful.HttpWrapper.CATEGORIES_URL;
import static radiomaster.restful.HttpWrapper.CATEGORIES_sub_URL;
import static radiomaster.restful.HttpWrapper.HTTP_METHOD_GET;
import radiomaster.restful.Response;

/**
 *
 * @author Ema
 */
public class view_categories extends javax.swing.JFrame implements HttpWrapper.OnCompletion {

    ArrayList<String> categories;
    ArrayList<String> subcategories;
    JMenuItem jsubmenu;
    ArrayList<String> id;
    int parent_id;

    /**
     * Creates new form view_categories
     */
    public view_categories() {
        initComponents();
        id = new ArrayList<>();
        categories = new ArrayList<>();
        subcategories = new ArrayList<>();
        jmenu.setText("Countries");
        jmenu1.setText("Categories");

        HttpWrapper wrapper = new HttpWrapper();
        

        wrapper.setURL(CATEGORIES_URL)
                //                .setOnCompletionListener(this)
                .setMethod(HTTP_METHOD_GET);
        wrapper.run();

        java.lang.reflect.Type tip = new TypeToken<Response<model_categories>>() {
        }.getType();

        Response<model_categories> odgovor = new Gson().fromJson(wrapper.getmResponseBody(), tip);

        for (model_categories item : odgovor.getContent()) {
//            System.out.println("title: " + item.getTitle() /*+ ", created at:" + item.getCreated_at() + ", updated at:" + item.getUpdated_at()*/);
            categories.add(item.getTitle());
            id.add(String.valueOf(item.getId()));

        }

        for (int i = 0; i < categories.size(); i++) {
            jsubmenu = new JMenuItem();
            jsubmenu.setText(categories.get(i));
           
            jmenu1.add(jsubmenu);
            
            jsubmenu.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                 for(int i=0; i<id.size();i++)
                    new view_subcategory(id.get(i)).setVisible(true);

                
            }
        });
        }

//        jsubmenu.addActionListener(new ActionListener() {
//            public void actionPerformed(ActionEvent e) {
//                new proba_jmenu().setVisible(true);
//                for (int i = 1; i < id.size(); i++) {
//                    wrapper_s.setURL(CATEGORIES_sub_URL + id.get(i))
//                            .setMethod(HTTP_METHOD_GET);
//                    wrapper_s.run();
//                    java.lang.reflect.Type tip_s = new TypeToken<Response<model_subcategories>>() {
//                    }.getType();
//                    Response<model_subcategories> odgovor_s = new Gson().fromJson(wrapper_s.getmResponseBody(), tip_s);
//                    for (model_subcategories item_s : odgovor_s.getContent()) {
//                        parent_id = item_s.getParent_id();
//                        System.out.println(item_s.getSlug());
//                    }
//
//                }
            }
//        });
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jmenubar = new javax.swing.JMenuBar();
        jmenu = new javax.swing.JMenu();
        jmenu1 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmenubar.add(jmenu);
        jmenubar.add(jmenu1);

        setJMenuBar(jmenubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmenu;
    private javax.swing.JMenu jmenu1;
    public static javax.swing.JMenuBar jmenubar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onSuccess(String successBody) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

    }

    @Override
    public void onError(String error) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
